server:
  port: 8080

spring:
  database:
    url:

  application:
    name: member-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # ??? ????? ?? ??? ???
          lower-case-service-id: true
    zookeeper:
      connecting-string: localhost:2181 # zookeeper ??
      discovery:
        enabled: true # Zookeeper ? ??? ??? ????? ??? ???? ?, ? ??? ???, Spring Boot? Zookeeper? ??? ???? ??? ??/??? ?? ???.
        register: true # ???(member-service)? Zookeeper ? ????? ??.
        instance-id: ${spring.application.name}:${random.value} # Zookeeper? ??? ?, ?member-service:asdf1234? ?? ?? ???? ??

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: member-group # Kafka ???? ?? ID. ?? ?? ID? ?? ????? ???? ?? ??? ??.??? member-group ??? ??? ???? ????, member ????? ???? ???.
      auto-offset-reset: earliest # ???? ?? ?? ?, ?? ?? ????? ???, ??? ?? ?? ????? ??? ??. earliest: ?? ?? ID? ??? ???? ??? ?? ??? ????? ??. latest: ???? ?? ?? ???? ??.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Kafka ???? key ? ????(??? ? ??)? ? ??? ???. ???? ??????? ?.
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Kafka ???? value ? ????? ???? ??????. ????? JSON ??? ???? ??? ? ??.

// ?? ?? ??
docker
????
??? ???
??
