server:
  port: 8082

spring:
  profiles:
    active: dev
  jwt:
    secret: lkcxjopvjwwkjlfisdlxcvnmnwpqlkjsdlfcxvnkdjwuekmn
  application:
    name: member-service
  datasource:
    url: jdbc:mysql://localhost:3306/member_db_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: songsong
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # ??? ????? ?? ??? ???
          lower-case-service-id: true
    zookeeper:
      connect-string: localhost:2181 # zookeeper ??
      discovery:
        enabled: true # Zookeeper ? ??? ??? ????? ??? ???? ?, ? ??? ???, Spring Boot? Zookeeper? ??? ???? ??? ??/??? ?? ???.
        register: true # ???(member-service)? Zookeeper ? ????? ??.
        instance-id: ${spring.application.name}:${random.value} # Zookeeper? ??? ?, ?member-service:asdf1234? ?? ?? ???? ??

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: member-group # Kafka ???? ?? ID. ?? ?? ID? ?? ????? ???? ?? ??? ??.??? member-group ??? ??? ???? ????, member ????? ???? ???.
      auto-offset-reset: earliest # ???? ?? ?? ?, ?? ?? ????? ???, ??? ?? ?? ????? ??? ??. earliest: ?? ?? ID? ??? ???? ??? ?? ??? ????? ??. latest: ???? ?? ?? ???? ??.
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Kafka ???? key ? ????(??? ? ??)? ? ??? ???. ???? ??????? ?.
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Kafka ???? value ? ????? ???? ??????. ????? JSON ??? ???? ??? ? ??.

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# ?? ?? ??
#docker
#????
# ??